// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"context"
	"errors"
	"io"
)

func await() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Flush().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// This implementation doesn't offer side-effect functionality when handling the error,
// so if you wish for any logging to happen it should be done in the functions generating the values used.
func awaitFallible(fallback any) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		switch fallback.(type) {
		case templ.Component, string:

		default:
			err = errors.New("invalid fallback argument passed: should be either a string or a Component")
			return err
		}

		children := templ.GetChildren(ctx)
		ctx = templ.ClearChildren(ctx)

		err = templ.Flush().Render(ctx, w)
		if err != nil {
			return err
		}

		// Using a buffer means any flushes inside it won't achieve anything;
		// we need all the contents to determine if the fallback should be rendered.
		buffer := new(bytes.Buffer)
		renderErr := children.Render(ctx, buffer)
		if renderErr == nil {
			_, err = buffer.WriteTo(w)
		} else {
			// Since this is intended for streaming, we are unable to react by redirecting to an error page.
			// Deliberately swallow the error and try to render a fallback instead.
			switch fb := fallback.(type) {
			case templ.Component:
				err = fb.Render(ctx, w)
			case string:
				_, err = io.WriteString(w, fb)
			default:
				panic("unhandled fallback type")
			}
		}
		if err != nil {
			return err
		}

		return
	})
}

var _ = templruntime.GeneratedTemplate
